services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - user-files:/app/storage
      # Mount flag at runtime; keep out of image
      - ./flag:/app/flag:ro
      # Keys volume not required for signing anymore; remove if unused
    environment:
      - PYTHONUNBUFFERED=1
      # DB connection details for future use by the API
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_NAME=tatou
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - TOKEN_TTL_SECONDS=${TOKEN_TTL_SECONDS}
      - DB_PORT=${DB_PORT}  # <-- for local dev convenience, ignore in production
      - STORAGE_DIR=${STORAGE_DIR}
      - ENABLE_PLUGIN_LOAD=${ENABLE_PLUGIN_LOAD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:11.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=tatou
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/tatou.sql:/docker-entrypoint-initdb.d/10-tatou.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root --password=$MARIADB_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=64M     # <-- use a unit and quote if using YAML key:value form
      - MEMORY_LIMIT=256M
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data:
  user-files:
